### ISSUE TITLE
Starting CF with wrong node version should fail gracefully

### ISSUE THREAD

**Issue by dethell** [pmcelhaney/counterfact#772]
If you start an instance of CF with node < 17 it gives this:

```
> npx counterfact openapi-v2.json api --open

file:///Users/SomeUser/some-code/node_modules/counterfact/dist/server/context-registry.js:17
        this.cache.set(path, structuredClone(context));
                       ^

ReferenceError: structuredClone is not defined
    at ContextRegistry.add (file:///Users/SomeUser/some-code/node_modules/counterfact/dist/server/context-registry.js:17:24)
    at new ContextRegistry (file:///Users/SomeUser/some-code/node_modules/counterfact/dist/server/context-registry.js:13:14)
    at counterfact (file:///Users/SomeUser/some-code/node_modules/counterfact/dist/server/app.js:35:29)
    at Command.main (file:///Users/SomeUser/some-code/node_modules/counterfact/bin/counterfact.js:72:27)
    at Command.listener [as _actionHandler] (/Users/SomeUser/some-code/node_modules/counterfact/node_modules/commander/lib/command.js:523:17)
    at /Users/SomeUser/some-code/node_modules/counterfact/node_modules/commander/lib/command.js:1375:65
    at Command._chainOrCall (/Users/SomeUser/some-code/node_modules/counterfact/node_modules/commander/lib/command.js:1272:12)
    at Command._parseCommand (/Users/SomeUser/some-code/node_modules/counterfact/node_modules/commander/lib/command.js:1375:27)
    at Command.parse (/Users/SomeUser/some-code/node_modules/counterfact/node_modules/commander/lib/command.js:989:10)
    at file:///Users/SomeUser/some-code/node_modules/counterfact/bin/counterfact.js:122:4
```

**Comment by pmcelhaney** [comment]
Weird, there's an engines field in the package.json that I assumed would have blocked that.
