### ISSUE TITLE
Error in json-faker data generation

### ISSUE THREAD

**Issue by dethell** [pmcelhaney/counterfact#827]
Getting this on some of our `.random()` endpoints:
```
 Error: unknown primitive "file" in /type
      at run (file:///Users/source/myapp/node_modules/json-schema-faker/dist/shared.js:5996:13)
      at jsf.generateWithContext (file:///Users/source/myapp/node_modules/json-schema-faker/dist/shared.js:6128:10)
      at jsf.generate (file:///Users/source/myapp/node_modules/json-schema-faker/dist/shared.js:6131:7)
      at Object.randomLegacy (file:///Users/source/myapp/node_modules/counterfact/dist/server/response-builder.js:89:39)
      at Object.random (file:///Users/source/myapp/node_modules/counterfact/dist/server/response-builder.js:63:33)
      at GET (file:///Users/source/myapp/projects/mock-server/api/.cache/activity/userInteractionAudit.js?cacheBust=1712089767633:2:28)
      at file:///Users/source/myapp/node_modules/counterfact/dist/server/registry.js:59:26
      at Dispatcher.request (file:///Users/source/myapp/node_modules/counterfact/dist/server/dispatcher.js:124:112)
      at middleware (file:///Users/source/myapp/node_modules/counterfact/dist/server/koa-middleware.js:33:43)
      at dispatch (/Users/source/myapp/node_modules/koa-compose/index.js:42:32)
```

**Comment by dethell** [comment]
You're right. `file` is not a valid type. Changing to `string` fixes the issue.

**Comment by dethell** [comment]
Makes sense.

**Comment by dethell** [comment]
Looking at this doc v2 of the OpenApi spec does allow `"type": "file"`: https://swagger.io/docs/specification/describing-responses/

v3 says to use `"type": "string"` but with `"format": "binary"`. Thoughts?

**Comment by pmcelhaney** [comment]
Okay, #829 eliminates the error but returns `undefined`. 

If the format is really binary (e.g. it's a JPEG vs. a CSV file), that's a gap in Counterfact's functionality at the moment. Can you create an issue for that?

**Comment by dethell** [comment]
Done: https://github.com/pmcelhaney/counterfact/issues/831
