### ISSUE TITLE
Prefer importing Jest globals (need to run elint --fix)

### ISSUE THREAD

**Issue by pmcelhaney** [pmcelhaney/counterfact#846]
#845 is blocked due to a new lint rule: 

https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/prefer-importing-jest-globals.md

The PR can be fixed by running `yarn lint --fix` and committing the changes. I could do that in about the same amount of time it took to create this issue, but wanted to leave a low hanging fruit out there for new contributors.

**Comment by dethell** [comment]
I took a shot at it and got this error:

```
TypeError: DeprecationError: 'originalKeywordKind' has been deprecated since v5.0.0 and can no longer be used. Use 'identifierToKeywordKind(identifier)' instead.
Occurred while linting /Users/davidethell/source/counterfact/src/server/tools.ts:14
Rule: "etc/no-misused-generics"
    at /Users/davidethell/source/counterfact/node_modules/typescript/lib/typescript.js:174086:13
    at IdentifierObject.<anonymous> (/Users/davidethell/source/counterfact/node_modules/typescript/lib/typescript.js:174116:7)
    at cb (/Users/davidethell/source/counterfact/node_modules/tsutils/util/usage.js:528:39)
    at Array.forEach (<anonymous>)
    at UsageWalker._handleFunctionLikeDeclaration (/Users/davidethell/source/counterfact/node_modules/tsutils/util/usage.js:604:25)
    at cb (/Users/davidethell/source/counterfact/node_modules/tsutils/util/usage.js:518:33)
    at visitNodes (/Users/davidethell/source/counterfact/node_modules/typescript/lib/typescript.js:28321:24)
    at forEachChildInClassDeclarationOrExpression (/Users/davidethell/source/counterfact/node_modules/typescript/lib/typescript.js:28372:197)
    at Object.forEachChild (/Users/davidethell/source/counterfact/node_modules/typescript/lib/typescript.js:28406:37)
    at forEachChild (/Users/davidethell/source/counterfact/node_modules/tsutils/util/usage.js:575:23)
error Command failed with exit code 2.
```

**Comment by pmcelhaney** [comment]
Run `yarn patch-package`. While you're at it can you add that to "postinstall"?

**Comment by dethell** [comment]
The renovate PR has been merged.
